name: VPS Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install and start Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled --tun=userspace-networking --socks5-server=localhost:1055 &
          sleep 5
          sudo tailscale up --authkey=${{ secrets.TS_AUTHKEY }} --hostname=gh-vps --accept-dns=true

       - name: Enable Tailscale Funnel properly
        run: |
          echo "Starting demo server on port 3000..."
          nohup python3 -m http.server 3000 >/dev/null 2>&1 &
          sleep 3
          echo "Enabling Funnel on localhost:3000 via port 8443..."
          sudo tailscale funnel --https=8443 --bg localhost:3000
          echo "✅ Funnel is active on port 8443"
          tailscale funnel status

      - name: Show Tailscale IP and Funnel info
        run: |
          echo "Tailscale IP:"
          cat tailscale_ip.txt
          echo "Funnel is running on port 3000"

      - name: Sleep to keep VPS alive
        run: sleep 3600

      - name: Backup VPS data and Tailscale state
        run: |
          tar -czf backup.tar.gz /etc /var || true

      - name: Upload VPS backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.tar.gz
